export const theme = {
  colors: {
    primary: "#eb994d",
    primaryLight: "#FFBC80",
    primaryFaded: "#FFB26A",
    secondary: "#FC595E",
    black: "#292929",
    shadow: "rgba(41,41,41,50)",
    lightBlack: "#434343",
    white: "#FAFAFA",
    grey: "#CCCCCC",
    input: "#ECECEC",
    placeholder: "#8C8C8C",
  },
  fonts: {
    bold: "Montserrat_700Bold",
    semiBold: "Montserrat_600SemiBold",
    medium: "Montserrat_500Medium",
    regular: "Montserrat_400Regular",
    light: "Montserrat_300Light",
    thin: "Montserrat_100Thin",
    thinItalic: "Montserrat_100Thin_Italic",
    alternateExtraLight: "MontserratAlternates_200ExtraLight",
    alternateLight: "MontserratAlternates_300Light",
    alternateRegular: "MontserratAlternates_400Regular",
    alternateMedium: "MontserratAlternates_500Medium",
    alternateSemiBold: "MontserratAlternates_600SemiBold",
    alternateBold: "MontserratAlternates_700Bold",
  },
};